main: de.rpgstupe.rpgplugin.Main
name: RPGPlugin
version: 1.0
author: me
description: An Example plugin
depend: [ProtocolLib]
commands:
  rpgclearinv:
    description: An example command
    usage: /rpgclearinv
    permission: myplugin.rpgclearinv
    permission-message: You don't have the myplugin.rpgclearinv permission.
  rpginventory:
    description: An example command
    usage: /rpginventory
    permission: myplugin.rpginventory
    permission-message: You don't have the myplugin.rpginventory permission.
  rpgcharacterselect:
    description: An example command
    usage: /rpgcharacterselect
    permission: myplugin.rpgcharacterselect
    permission-message: You don't have the myplugin.rpgcharacterselect permission.
  rpgcreate:
    description: An example command
    usage: /rpgcreate
    permission: myplugin.rpgcreate
    permission-message: You don't have the myplugin.rpgcreate permission.
  rpgchangeinventory:
    description: An example command
    usage: /rpgchangeinventory
    permission: myplugin.rpgchangeinventory
    permission-message: You don't have the myplugin.rpgchangeinventory permission.
  rpgchangecharacter:
    description: An example command
    usage: /rpgchangecharacter
    permission: myplugin.rpgchangecharacter
    permission-message: You don't have the myplugin.rpgchangecharacter permission.
  mycommand:
    description: An example command
    usage: /mycommand
    permission: myplugin.mycommand
    permission-message: You don't have the myplugin.mycommand permission.
  myinventory:
    description: An example command
    usage: /myinventory
    permission: myplugin.myinventory
    permission-message: You don't have the myplugin.myinventory permission.
  myskill:
    description: An example command
    usage: /myskill
    permission: myplugin.myskill
    permission-message: You don't have the myplugin.myskill permission.
  myrespawn:
    description: An example command
    usage: /myrespawn
    permission: myplugin.myrespawn
    permission-message: You don't have the myplugin.myrespawn permission.
  mydamagetext:
    description: An example command
    usage: /mydamagetext
    permission: myplugin.mydamagetext
    permission-message: You don't have the myplugin.mydamagetext permission.
  killall:
    description: An example command
    usage: /killall
    permission: myplugin.killall
    permission-message: You don't have the myplugin.killall permission.