main: de.rpgstupe.testplugin.Main
name: TestPlugin
version: 1.0
author: Alpacca
description: An Example plugin
commands:
  mycommand:
    description: An example command
    usage: /mycommand
    permission: myplugin.mycommand
    permission-message: You don't have the myplugin.mycommand permission.